controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/auth

nelmio_api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui

