parameters:
    openweather_api_key: '%env(OPENWEATHERMAP_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\WeatherService:
        arguments:
            $openWeatherKey: '%openweather_api_key%'
